### ISSUE TITLE
[HU44]- Base de datos de Myvet Ecommerce

### ISSUE THREAD

**Issue by HernanRT** [Yanina-Unrein/MyVet_TSDWAD#169]
Feature: Creación de una base de datos para una tienda en línea

Como administrador de una tienda en línea
Quiero una base de datos en SQL que almacene información sobre sucursales, tarjetas de pago, usuarios, ventas, productos, categorías, direcciones y medios de pago
Para poder administrar la tienda de manera efectiva y eficiente.

Escenario: Crear una base de datos en SQL
Dado: que soy el administrador de la tienda en línea
Cuando: deseo crear una base de datos en SQL
Entonces: la base de datos debe incluir :

Tablas principales:
- Sucursales: debe incluir información como el nombre, dirección, ciudad, país y el número de teléfono de cada sucursal

- Tarjeta_de_pago:  debe incluir los datos como nombre, apellido y DNI del titular de la tarjeta, número y fecha de caducidad de la misma, código de seguridad.

- Usuario: debe incluir nombre, apellido, teléfono, email. contraseña, DNI y dirección.

- Venta: debe incluir la fecha de la venta, el estado de la misma, el total, el método de pago, y el id del usuario que realizo la compra.

- Productos: debe incluir el nombre del producto, descripción, precio, marca, cantidad , una imagen del producto(url), fecha de ingreso, fecha de modificación  y activo.

- Categorías: debe incluir el nombre de la categoría y una descripción. 

- Direccion: debe incluir el id del usuario, calle, altura, piso, departamento, código postal y observaciones.

- Medios_de_pago: debe incluir el tipo de medio de pago y una descripción

Tablas intermedias:
- Detalle_venta: debe incluir información específica de cada producto vendido en una transacción, como el id de la venta, el id del producto y la cantidad.

- Producto_categoria: Tabla intermedia que relaciona cada producto con su categoría correspondiente, debe incluir el id del producto y el id de la categoría.

- Producto_sucursales: tabla que relaciona los productos con las sucursales que los almacenan y/o venden. Debe incluir el id de la sucursal, el id del producto y el stock disponible.

**Comment by Yanina-Unrein** [comment]
#TK41 - Creación de tabla tarjeta_de_pago
