### ISSUE TITLE
[HU11] - Base de datos

### ISSUE THREAD

**Issue by Loreaylen** [Yanina-Unrein/MyVet_TSDWAD#24]
Como administrador, quiero disponer de una base de datos para almacenar, acceder y modificar  la información de los clientes.

```
Escenario: Acceso a base de datos
Dado: El cliente provee sus datos y los de sus animales.
Cuando: Se realiza una consulta a la base de datos
Entonces: Se visualizan los datos solicitados.
```

**Comment by Loreaylen** [comment]
#TK05

**Comment by Loreaylen** [comment]
#TK06

**Comment by Yanina-Unrein** [comment]
#TK21 -  Creación tablas intermedias Asigna y Profesional_Sucursal

**Comment by MundoViolento** [comment]
#TK24 - Creación tabla BD Sucursales

**Comment by FlorenciaItati** [comment]
#TK26 - Creación tabla Tratamiento

**Comment by Uriel-98** [comment]
#TK27 - Creación de tabla Visita
