### ISSUE TITLE
#TK96 - Tablero Dashboard Usuario 

### ISSUE THREAD

**Issue by Uriel-98** [Yanina-Unrein/MyVet_TSDWAD#293]
El rol USUARIO registrado solo puede ver su Dashboard para editar su perfil

**Comment by HernanRT** [comment]
-TKM97 Crear Tablero de control para usuarios: Mostrar catálogo . Seleccionar para comprar. 
Crear templates home y templates de cada endpoint (login-logout-registrarse-perfil-vista de usuarios, productos agregar y ver productos)
