### ISSUE TITLE
[HU02] - Visualizar página de contacto

### ISSUE THREAD

**Issue by janu-ss** [Yanina-Unrein/MyVet_TSDWAD#7]
Como administrador quiero que el usuario visualice la página de contacto

Caso de uso:

Escenario: Visualizar página de contacto
	Dado: El usuario ingresa al sitio web
	Cuando: Al entrar se muestra la página de inicio, dentro del navegador accede a la opcion: "Contacto"
	Entonces: Se visualizará una página con las siguientes características:
			- Header que contenga logo de la veterinaria y un navegador
			- Un navegador con las opciones: Inicio, Quienes somos, Servicios, Sucursales, Tienda, Contacto
			- Un body con una imagen de animales de fondo
			- Un formulario para completar con datos personales, segun: Nombre, Apellido, Mail, Telefono,
                          Tipo de mascota con un menu desplegable para elegir, Asunto, Mensaje y un Boton para Enviar.
			- Un footer que contenga un botón de emergencias.

**Comment by Loreaylen** [comment]
#TK10 - Estructura de página de contacto
